// Copyright (c) 2020 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

= Contributing

Contributions to the KhronosGroup/assetcreation-models repository are
welcome.

Contributions may be in the form of Issues proposing a change, or Pull
Requests containing fixes for, or additions to the repository.

Please keep contributions focused on solving a single issue or bug.

== Copyright Notice and License Template

If you are adding a new file, it must be under one of the following
licenses:

  * Creative Commons Attribution 4.0 International, for specification text
    (for example, link:asset-creation-guidelines/RealtimeAssetCreationGuidelines.md[`asset-creation-guidelines/RealtimeAssetCreationGuidelines.md`])
  * Apache 2.0, for all other changes (for example,
    link:asset-creation-guidelines/convert-pdf.sh[`asset-creation-guidelines/convert-pdf.sh`])

We use a short license in each file consisting of just the copyright
statement and the SPDX license identifier of the license applying to that
file, and link to the full license text from link:LICENSE.adoc.

When publishing specifications that Ratified by the Khronos Board of
Promoters on the Khronos website, those specific generated documents (PDFs)
carry a proprietary Khronos Specification License.
The content of such documents is otherwise identical to documents in this
repository.

== Contributor License Agreement

When you propose a pull request to this repository, you must execute the
Khronos Mixed Repository Contributor License Agreement, to confirm you own
your work and are granting Khronos the neccessary permissions to
redistribute it under our licenses.
