// Copyright 2020 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

= COPYING file for the KhronosGroup/assetcreation-models project

== Licenses

The assetcreation-models project uses several licenses.

* The source files (in Markdown, asciidoctor and other formats) for the
  Specification and supporting documentation are licensed under the Creative
  Commons Attribution 4.0 International License (SPDX license identifier
  "`CC-BY`").
* Header files, scripts, programs, XML files, and other tooling used or
  generated as part of the build process are typically licensed under the
  Apache License, Version 2.0 (SPDX license identifier "`Apache-2.0`").
* Some contributed samples are licensed under the CC0 1.0 Universal "`Public
  Domain Dedication`" license (SPDX license identifier "`CC0-1.0`")

Users outside Khronos who create and post Specifications from this
repository, whether modified or not, should use the CC-BY 4.0 license on the
*output* documents (HTML, PDF, etc.) they generate. This is the default.


== Frequently Asked Questions

Q: Why are the HTML and PDF Specifications posted on Khronos' website under
a license which is neither CC-BY nor Apache-2.0?

A: The Specifications posted by Khronos are licensed under the proprietary
Khronos Specification License. Only these Specifications are Ratified by the
Khronos Board of Promoters, and therefore they are the only Specifications
covered by the Khronos Intellectual Property Rights Policy.


Q: Does Khronos allow the creation and distribution of modified versions of
the specifications, such as translations to other languages?

A: Yes. Such modified Specifications, since they are not created by Khronos,
should be placed under the CC-BY license. If you believe your modifications
are of general interest, consider contributing them back by making a pull
request (PR) on the assetcreation-models project.


Q: Can I contribute changes to the assetcreation-models repository?

A: Yes, by opening an Issue or Pull Request (PR) on the
link:https://github.com/KhronosGroup/assetcreation-models/[assetcreation-models] Github
project.
You must execute a click-through Contributor License Agreement, which brings
your changes under the umbrella of the Khronos IP policy.


Q: Can you change the license on your files so they're compatible with my
license?

A: In cases of GPL-licensed projects which cannot incorporate Khronos code
licensed only under Apache 2.0, we may be able to dual-license such files
under Apache 2.0 OR MIT. If this is a requirement for your use case, please
open an Issue on the github repository giving the details.
